name: see_vee
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  provider: ^6.1.1
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: "Jetbrains Mono"
      fonts:
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
        - asset: assets/fonts/JetBrainsMono-SemiBold.ttf
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Thin.ttf
